draw_set_alpha(1)
draw_set_font(font_exo)
draw_set_halign(fa_right)
draw_set_valign(fa_top)
draw_text_transformed(room_width-20,20,"0000000",1,1,0)
draw_set_valign(fa_bottom)
draw_text_transformed(room_width-20,room_height - 20,"AT Lv.16",1,1,0)
draw_set_halign(fa_left)
draw_text_transformed(20,room_height - 20,"| Igallta",1,1,0)